=== TanThienDao/Project5A8A9/Services/App_Data/MemberSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xsd:element name="Members">
    <xsd:sequence maxOccurs="unbounded">
      <xsd:element name="Member" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequences>
            <xsd:element name="user_name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="password" type="xsd:string" minOccurs="1" maxOccurs="1"/>
          </xsd:sequences>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:element>
</xsd:schema>

=== TanThienDao/Project5A8A9/Project5A8A9/App_Data/Member.xml
<?xml version="1.0" encoding="utf-8"?>
<Members xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MemberSchema.xsd">
  <Member>
    <user_name>Test</user_name>
    <password>check</password>
  </Member>
  <Member>
    <user_name>Test2</user_name>
    <password>check2</password>
  </Member>
  <Member>
    <user_name>TestEncrypt</user_name>
    <password>Qvm5cOQ/H6E=</password>
  </Member>
  <Member>
    <user_name>eee</user_name>
    <password>Tm/slU4z00s=</password>
  </Member>
</Members>

=== TanThienDao/Project5A8A9/Services/App_Data/Member.xml
<?xml version="1.0" encoding="utf-8"?>
<Members>
  <!--xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MemberSchema.xsd">-->
  <Member>
    <user_name>Test</user_name>
    <password>check</password>
  </Member>
  <Member>
    <user_name>Test2</user_name>
    <password>check2</password>
  </Member>
  <Member>
    <user_name>TanTest</user_name>
    <password>VXiXcyCjf2vJkG/0B33XuA==</password>
  </Member>
  <Member>
    <user_name>TanTest2</user_name>
    <password>VXiXcyCjf2vJkG/0B33XuA==</password>
  </Member>
  <Member>
    <user_name>TanTest3</user_name>
    <password>VXiXcyCjf2vJkG/0B33XuA==</password>
  </Member>
</Members>
